"""remove bool types and add just premise_type column

Revision ID: 12973b0f1a76
Revises: 1ba26a02fd40
Create Date: 2026-10-06 17:18:43.010992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12973b0f1a76'
down_revision: Union[str, Sequence[str], None] = '1ba26a02fd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premises', sa.Column('premise_type', sa.String(), nullable=False))
    op.drop_column('premises', 'is_warehouse')
    op.drop_column('premises', 'is_apartments')
    op.drop_column('premises', 'is_house')
    op.drop_column('premises', 'is_countryHouse')
    op.drop_column('premises', 'is_commercialPremise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premises', sa.Column('is_commercialPremise', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('premises', sa.Column('is_countryHouse', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('premises', sa.Column('is_house', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('premises', sa.Column('is_apartments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('premises', sa.Column('is_warehouse', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('premises', 'premise_type')
    # ### end Alembic commands ###
