"""delete premise type table and add his columns in premises table

Revision ID: 1ba26a02fd40
Revises: 9305bf3f76cb
Create Date: 2026-10-05 13:26:41.638643

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ba26a02fd40"
down_revision: Union[str, Sequence[str], None] = "9305bf3f76cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("premises", sa.Column("is_apartments", sa.Boolean(), nullable=False))
    op.add_column("premises", sa.Column("is_house", sa.Boolean(), nullable=False))
    op.add_column(
        "premises", sa.Column("is_countryHouse", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "premises", sa.Column("is_commercialPremise", sa.Boolean(), nullable=False)
    )
    op.add_column("premises", sa.Column("is_warehouse", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "premises",
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("premises_type_id_fkey"), "premises", "premise_type", ["type_id"], ["id"]
    )
    op.create_index(op.f("ix_premises_type_id"), "premises", ["type_id"], unique=False)
    op.drop_column("premises", "is_warehouse")
    op.drop_column("premises", "is_commercialPremise")
    op.drop_column("premises", "is_countryHouse")
    op.drop_column("premises", "is_house")
    op.drop_column("premises", "is_apartments")
    op.create_table(
        "premise_type",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("is_apartments", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_house", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_countryHouse", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "is_commercialPremise", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("is_warehouse", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("premise_type_pkey")),
    )
    op.create_index(op.f("ix_premise_type_id"), "premise_type", ["id"], unique=True)
    # ### end Alembic commands ###
