"""delete user_premises_id column  from users table

Revision ID: 2a475e15ddf0
Revises: 7d0de28fce8b
Create Date: 2026-10-01 16:20:45.544055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a475e15ddf0'
down_revision: Union[str, Sequence[str], None] = '7d0de28fce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_user_premises_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'user_premises_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_premises_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_user_premises_id_fkey'), 'users', 'premises', ['user_premises_id'], ['id'])
    # ### end Alembic commands ###
