"""a little features in user and premise models in columns

Revision ID: 2cb25dc32d92
Revises: ef5a9a8cd008
Create Date: 2026-09-30 16:18:26.948534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb25dc32d92'
down_revision: Union[str, Sequence[str], None] = 'ef5a9a8cd008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
