"""delete roles table and roles_id column in user table

Revision ID: 3a3babb4bbaf
Revises: 8302e77d62d5
Create Date: 2026-10-08 15:40:00.577497

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a3babb4bbaf"
down_revision: Union[str, Sequence[str], None] = "8302e77d62d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), nullable=False))
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("users_role_id_fkey"), "users", "roles", ["role_id"], ["id"]
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.drop_column("users", "role")
    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("is_landlord", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_modDisputes", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_modListings", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_superMod", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    # ### end Alembic commands ###
