"""add new column for relationship

Revision ID: 6119bbee79f2
Revises: 8c32e2be3490
Create Date: 2026-09-21 13:02:58.974417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6119bbee79f2'
down_revision: Union[str, Sequence[str], None] = '8c32e2be3490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('premise_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('renter_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('landlord_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bookings_landlord_id'), 'bookings', ['landlord_id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_id'), 'bookings', ['payment_id'], unique=False)
    op.create_index(op.f('ix_bookings_premise_id'), 'bookings', ['premise_id'], unique=False)
    op.create_index(op.f('ix_bookings_renter_id'), 'bookings', ['renter_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['renter_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'premises', ['premise_id'], ['id'])
    op.add_column('disputes', sa.Column('renter_id', sa.Integer(), nullable=False))
    op.add_column('disputes', sa.Column('landlord_id', sa.Integer(), nullable=False))
    op.add_column('disputes', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.add_column('disputes', sa.Column('mod_dispute', sa.Integer(), nullable=False))
    op.add_column('disputes', sa.Column('reason', sa.TEXT(), nullable=False))
    op.create_index(op.f('ix_disputes_booking_id'), 'disputes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_disputes_landlord_id'), 'disputes', ['landlord_id'], unique=False)
    op.create_index(op.f('ix_disputes_mod_dispute'), 'disputes', ['mod_dispute'], unique=False)
    op.create_index(op.f('ix_disputes_renter_id'), 'disputes', ['renter_id'], unique=False)
    op.create_foreign_key(None, 'disputes', 'users', ['mod_dispute'], ['id'])
    op.create_foreign_key(None, 'disputes', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key(None, 'disputes', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'disputes', 'users', ['renter_id'], ['id'])
    op.add_column('payments', sa.Column('from_user_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('to_landlord_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('for_premise_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_payments_for_premise_id'), 'payments', ['for_premise_id'], unique=False)
    op.create_index(op.f('ix_payments_from_user_id'), 'payments', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_payments_to_landlord_id'), 'payments', ['to_landlord_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['to_landlord_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'premises', ['for_premise_id'], ['id'])
    op.add_column('premises', sa.Column('type_id', sa.Integer(), nullable=False))
    op.add_column('premises', sa.Column('address_id', sa.Integer(), nullable=False))
    op.add_column('premises', sa.Column('feature_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_premises_address_id'), 'premises', ['address_id'], unique=False)
    op.create_index(op.f('ix_premises_feature_id'), 'premises', ['feature_id'], unique=False)
    op.create_index(op.f('ix_premises_type_id'), 'premises', ['type_id'], unique=False)
    op.create_foreign_key(None, 'premises', 'premise_feature', ['feature_id'], ['id'])
    op.create_foreign_key(None, 'premises', 'premise_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'premises', 'premise_address', ['address_id'], ['id'])
    op.add_column('users', sa.Column('contact_number', sa.String(length=12), nullable=False))
    op.add_column('users', sa.Column('favorite_premises', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_contact_number'), 'users', ['contact_number'], unique=True)
    op.create_index(op.f('ix_users_favorite_premises'), 'users', ['favorite_premises'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'premises', ['favorite_premises'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_favorite_premises'), table_name='users')
    op.drop_index(op.f('ix_users_contact_number'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'favorite_premises')
    op.drop_column('users', 'contact_number')
    op.drop_constraint(None, 'premises', type_='foreignkey')
    op.drop_constraint(None, 'premises', type_='foreignkey')
    op.drop_constraint(None, 'premises', type_='foreignkey')
    op.drop_index(op.f('ix_premises_type_id'), table_name='premises')
    op.drop_index(op.f('ix_premises_feature_id'), table_name='premises')
    op.drop_index(op.f('ix_premises_address_id'), table_name='premises')
    op.drop_column('premises', 'feature_id')
    op.drop_column('premises', 'address_id')
    op.drop_column('premises', 'type_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_to_landlord_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_from_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_for_premise_id'), table_name='payments')
    op.drop_column('payments', 'for_premise_id')
    op.drop_column('payments', 'to_landlord_id')
    op.drop_column('payments', 'from_user_id')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_index(op.f('ix_disputes_renter_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_mod_dispute'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_landlord_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_booking_id'), table_name='disputes')
    op.drop_column('disputes', 'reason')
    op.drop_column('disputes', 'mod_dispute')
    op.drop_column('disputes', 'booking_id')
    op.drop_column('disputes', 'landlord_id')
    op.drop_column('disputes', 'renter_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_renter_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_premise_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_landlord_id'), table_name='bookings')
    op.drop_column('bookings', 'payment_id')
    op.drop_column('bookings', 'landlord_id')
    op.drop_column('bookings', 'renter_id')
    op.drop_column('bookings', 'premise_id')
    # ### end Alembic commands ###
