"""nullable true in user table

Revision ID: 6eac19bb0854
Revises: 3a3babb4bbaf
Create Date: 2026-10-09 11:54:45.300454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eac19bb0854'
down_revision: Union[str, Sequence[str], None] = '3a3babb4bbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
