"""delete cascade param in premise table

Revision ID: 9305bf3f76cb
Revises: 2a475e15ddf0
Create Date: 2026-10-01 17:04:37.596073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9305bf3f76cb'
down_revision: Union[str, Sequence[str], None] = '2a475e15ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_favorite_premises'), table_name='users')
    op.drop_constraint(op.f('users_favorite_premises_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'favorite_premises')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_premises', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_favorite_premises_fkey'), 'users', 'premises', ['favorite_premises'], ['id'])
    op.create_index(op.f('ix_users_favorite_premises'), 'users', ['favorite_premises'], unique=False)
    # ### end Alembic commands ###
