"""another delete params in user/premise columns

Revision ID: 93b6c7ecc55a
Revises: a8ddad9b70e4
Create Date: 2026-10-01 15:05:06.166291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b6c7ecc55a'
down_revision: Union[str, Sequence[str], None] = 'a8ddad9b70e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
