"""fix data types in models

Revision ID: 9d244799717d
Revises: 542ef76ab557
Create Date: 2026-09-27 12:07:52.655649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d244799717d'
down_revision: Union[str, Sequence[str], None] = '542ef76ab557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'total',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('premise_feature', 'area',
               existing_type=sa.NUMERIC(precision=1, scale=0),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('premise_feature', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('premise_feature', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('premise_feature', 'area',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=1, scale=0),
               existing_nullable=False)
    op.alter_column('payments', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
