"""add user_premises_id column in user model

Revision ID: a3373bf28e1e
Revises: 93b6c7ecc55a
Create Date: 2026-10-01 15:14:27.174455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3373bf28e1e'
down_revision: Union[str, Sequence[str], None] = '93b6c7ecc55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_premises_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'premises', ['user_premises_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_premises_id')
    # ### end Alembic commands ###
